// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCltIpLkl9FIVMOJXexo7CRafw0T2wHCHo',
    appId: '1:543499541523:web:924305926668638ea6f3e6',
    messagingSenderId: '543499541523',
    projectId: 'agman-5ba42',
    authDomain: 'agman-5ba42.firebaseapp.com',
    storageBucket: 'agman-5ba42.appspot.com',
    measurementId: 'G-F41DYMSZ7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_refT7z8ufO40geefyX-xU-G2SoaceEg',
    appId: '1:543499541523:android:dc61f2b8c253684ca6f3e6',
    messagingSenderId: '543499541523',
    projectId: 'agman-5ba42',
    storageBucket: 'agman-5ba42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAxunmWzE_QgupZaXTdtNj-DORQamTRHk',
    appId: '1:543499541523:ios:61f63c37bddbf922a6f3e6',
    messagingSenderId: '543499541523',
    projectId: 'agman-5ba42',
    storageBucket: 'agman-5ba42.appspot.com',
    iosBundleId: 'com.example.agman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAxunmWzE_QgupZaXTdtNj-DORQamTRHk',
    appId: '1:543499541523:ios:61f63c37bddbf922a6f3e6',
    messagingSenderId: '543499541523',
    projectId: 'agman-5ba42',
    storageBucket: 'agman-5ba42.appspot.com',
    iosBundleId: 'com.example.agman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCltIpLkl9FIVMOJXexo7CRafw0T2wHCHo',
    appId: '1:543499541523:web:65a5151460c4c3f1a6f3e6',
    messagingSenderId: '543499541523',
    projectId: 'agman-5ba42',
    authDomain: 'agman-5ba42.firebaseapp.com',
    storageBucket: 'agman-5ba42.appspot.com',
    measurementId: 'G-P910Z48YTB',
  );
}
